### ISSUE TITLE
Postgres local instance main.go having issues reading the db file

### ISSUE THREAD

**Issue by rajvadranam** [divyam234/teldrive#122]
Error:
```
teldrive     | panic: open /teldrive.db: is a directory
teldrive     |
teldrive     | goroutine 1 [running]:
teldrive     | github.com/divyam234/teldrive/pkg/database.InitDB()
teldrive     |  github.com/divyam234/teldrive/pkg/database/database.go:81 +0x5e5
teldrive     | main.main()
teldrive     |  ./main.go:29 +0xd7
```

docker-file

```
version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/teldrive
    restart: always
    container_name: teldrive
    volumes:
      - /mnt/c/deploy/teldrive/teldrive.db:/teldrive.db:rw
      - /mnt/c/deploy/teldrive/logs:/logs:rw
    env_file: teldrive.env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    container_name: teldrive_db
    restart: always
    environment:
      - POSTGRES_USER=teldrive
      - POSTGRES_PASSWORD=1234
    volumes:
      - teldrive_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "teldrive"]
      interval: 10s
      start_period: 30s

volumes:
  teldrive_db:
```
