### ISSUE TITLE
the program won't start

### ISSUE THREAD

**Issue by JoaGamo** [divyam234/teldrive#188]
Hello, i'm on a debian container, privileged of course (proxmox) trying to use this app. i cant access the discord server for some reason so I can only ask here
I've tried both docker compose with everything that was required in the config configured properly, same with a manually compiled version of the app (and trying to run with ./teldrive run --config config.toml) but the program exits instantly without a log.
I've configured the [log] to -1 for debugging purposes but it doesn't output anything. when I check with 'docker compose ps' the container is in a restart(1) state all the time (and the docker logs are also empty)
edit: the issue persists with a plain new debian VM
this is my config

```toml
[db]
  data-source = "postgres://teldrive:secret@192.168.0.xx/teldrive?sslmode=disable"
  log-level = 1

  [db.migrate]
    enable = true

  [db.pool]
    max-idle-connections = 25
    max-lifetime = "10m"
    max-open-connections = 25

[jwt]
  allowed-users = [""]
  secret = "redacted"
  session-time = "30d"

[log]
  development = true
  level = -1

[server]
  graceful-shutdown = "15s"
  port = 8080

[tg]
  app-hash = "redacted"
  app-id = 2xxxx...
  app-version = "4.6.3 K"
  bg-bots-limit = 5
  device-model = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"
  disable-stream-bots = false
  lang-code = "en"
  lang-pack = "webk"
  rate = 100
  rate-burst = 5
  rate-limit = true
  session-file = ""
  system-lang-code = "en-US"
  system-version = "Win32"

  [tg.uploads]
    encryption-key = "keytest"
    retention = "7d"
    threads = 8
```
what im doing wrong?
