### ISSUE TITLE
ERROR "Cannot read properties of undefined (reading 'currentPage')" - after moving to new host

### ISSUE THREAD

**Issue by bpawnzZ** [divyam234/teldrive#318]
Hello all. To start with I am using 'docker-compose.postgres.yml'.  Been using Teldrive for 6ish months and love it.  I yesterday move from one VPS host to another. I zipped the teldrive directory and moved it to new host and unzipped it and went to set everything up.  When i log in I am getting the ERROR "Cannot read properties of undefined (reading 'currentPage')".  Does anyone know how I can fix this!!  I have a good ammount of stuff on Teldrive and dont want to lose it!  Thank you for your help..  I really appreciate it!

![photo_2024-07-19_19-05-01](https://github.com/user-attachments/assets/24549ad1-b015-4be2-b106-99c3ad827383)

I can connect to DB so I really dont know why it is doing this.
![photo_2024-07-19_19-12-40](https://github.com/user-attachments/assets/7bb3c98d-1ce5-4e9f-9bb8-7fe47756241c)

**Comment by bpawnzZ** [comment]
Ok.. I just reverted to a previous build to teldrive and it is working.  My newly built image seemed to be the issue.  For the dev there might be a issue with your code that just happened for people self hosting postgres.

For anyone with the same issue.  Feel free to pull this image and use it.. Its working and built a little over a week ago. 'bpawnzz/teldrivecustom:v1'

**Comment by bpawnzZ** [comment]
I was reading somewhere about changes in sql images or something  Below is my compose file.  do u see any issues with any thing.. Just would like to be able to build the newest version.  It is gettinb better so i rebuild every now and then.

````
version: "3.8"

services:
  server:
    image: bpawnzz/teldrivecustom:v1
    restart: always
    hostname: teldrive
    container_name: teldrive
    volumes:
      - ./session.db:/session.db:rw
      - ./config.toml:/config.toml
    ports:
      - 1234:8080
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 1.1.1.1

  db:
    image: groonga/pgroonga
    container_name: teldrive_db
    hostname: postgresTeldrive
    restart: always
    environment:
      - POSTGRES_USER=teldrive
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "teldrive"]
      interval: 10s
      start_period: 30s
    dns:
      - 1.1.1.1
 ````
