### ISSUE TITLE
ERROR "Cannot read properties of undefined (reading 'currentPage')" - after build of new code

### ISSUE THREAD

**Issue by bpawnzZ** [divyam234/teldrive#323]
I posted this last week and received no response but it was marked closed???.  Just did a git pull of most recent code and still same issue..  Can u help me out with why this going on or how i can fix??  Thank you

Hello all. To start with I am using 'docker-compose.postgres.yml'. Been using Teldrive for 6ish months and love it. I have a build that is prolly 3 weeks old and works as usual with no problem. Bur for past 2 weeks if i build with updated code from github I get the error below.  However if I rollback  to previous build it is no problem.  Why is this happening and did something break or change??  And if something did change how can i fix it on my end.
![350621830-24549ad1-b015-4be2-b106-99c3ad827383](https://github.com/user-attachments/assets/3e0b72f2-a0c0-42fe-8b49-de97c93d07d6)
I can connect to DB so I really dont know why it is doing this.
![350625711-7bb3c98d-1ce5-4e9f-9bb8-7fe47756241c](https://github.com/user-attachments/assets/5f59d67d-510c-423d-b075-77ac6c6ad198)

````
version: "3.8"

services:
  server:
    image: bpawnzz/teldrivecustom:v1
    restart: always
    hostname: teldrive
    container_name: teldrive
    volumes:
      - ./session.db:/session.db:rw
      - ./config.toml:/config.toml
    ports:
      - 1234:8080
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 1.1.1.1

  db:
    image: groonga/pgroonga
    container_name: teldrive_db
    hostname: postgresTeldrive
    restart: always
    environment:
      - POSTGRES_USER=teldrive
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "teldrive"]
      interval: 10s
      start_period: 30s
    dns:
      - 1.1.1.1
````
